### PR TITLE
Switch to Bionic Beaver and get rid of Chef

### PR DESCRIPTION
**Pull request by mo-nathan**

### CODE REVIEW

**Comment by JoeCohen** [comment]
(Following essentially duplicates my email to mo-developers.)
This hits a problem when starting from absolute scratch (installing VirtualBox and Vagrant, cloning the repo)
```ruby
vagrant@vagrant:/vagrant/mushroom-observer$ rails test 
Coverage report generated for MiniTest to /vagrant/mushroom-observer/coverage. 551 / 1959 LOC (28.13%) covered.[
Coveralls] Outside the CI environment, not sending data.Traceback (most recent call last):
	 80: from bin/rails:4:in `<main>'
	 ...
	 3: from /vagrant/mushroom-observer/app/classes/gmaps.rb:48:in `<module:GM>'
	 2: from /home/vagrant/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	 1: from /home/vagrant/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'/home/vagrant/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `initialize': 
No such file or directory @ rb_sysopen - /vagrant/mushroom-observer/config/gmaps_api_key.yml (Errno::ENOENT)
```
So it looks like we need something like the following (I don't know where it belongs):
```bash
if [ ! -f config/gmaps_api_key.yml ]; then
    cp config/gmaps_api_key.yml-template config/gmaps_api_key.yml
    echo Copied config/gmaps_api_key.yml-template
else
    echo gmaps_api_key.yml exists
fi
```
See https://github.com/MushroomObserver/mushroom-observer/commit/66a8c7a3614e53f199bcaacb071f5e21fab2018b

**Comment by JoeCohen** [comment]
Do we still need the file `developer-startup/build`?
If so, should it continue to contain `librarian-chef install`?

**Comment by JoeCohen** [comment]
Re `config/gmaps_api_key.yml`:
Would it make sense to also tell git to ignore this file. (Might avoid some confusion.)

**Comment by pellaea** [comment]
It should already be in the .gitignore file.

**Comment by JoeCohen** [comment]
Is there a _very easy_ way to force the scripts to run using the "correct" version of Ruby.
(I kept running into the problem of their running with 2.7.1. I'm not sure why that was the case, as I'm pretty sure that 2.6.6 was the default Ruby version, and in .ruby-version in the trunc-fix branch.) 
If this is not _very easy_ forget about it. It's a weird edge case, and it's easy to work around.

**Comment by pellaea** [comment]
I could have sworn rvm was supposed to make that easy.  I thought it used
whatever was in .ruby-version.  Isn't there also a command-line command
that tells rvm which version to use?  I can't fathom why it keeps running
the wrong version for you.

**Comment by JoeCohen** [comment]
@pellaea: I had installed 2.7.1 for an experimental branch, and the issue is obviously related to that. But I still can't fathom it. If it isn't super-easy to fix, @mo-nathan should just forget about it.

**Comment by JoeCohen** [comment]
Is 14.04 what I should be seeing after `vagrant ssh`? 
>`Joe@Josephs-MacBook-Pro-5 developer-startup % vagrant ssh`
`Welcome to Ubuntu` **14.04.3**` LTS (GNU/Linux 3.13.0-67-generic x86_64)`
`...`
`New release` '**16.04.6 LTS**' `available`.
`Run 'do-release-upgrade' to upgrade to it`.

**Comment by JoeCohen** [comment]
I hope this makes sense:
After `vagrant ssh`, should the response be a newer version of Ubuntu, in particular, Bionic Beaver.
Would that save time in mo-dev?
>`Joe@Josephs-MacBook-Pro-5 developer-startup % vagrant ssh`
`Welcome to Ubuntu` **14.04.3** `LTS (GNU/Linux 3.13.0-67-generic x86_64)`
`...`
`New release` '16.04.6 LTS' `available.`

**Comment by JoeCohen** [comment]
At the end of output after
```
```
I see the following. I don-t know if it's what's expected
```
Installed exiftool
Already up-to-date.
Traceback (most recent call last):
	4: from /home/vagrant/.rvm/rubies/ruby-2.6.6/bin/ruby_executable_hooks:24:in `<main>'
	3: from /home/vagrant/.rvm/rubies/ruby-2.6.6/bin/ruby_executable_hooks:24:in `eval'
	2: from /home/vagrant/.rvm/rubies/ruby-2.6.6/bin/bundle:23:in `<main>'
	1: from /home/vagrant/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
/home/vagrant/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0/rubygems.rb:284:in `find_spec_for_exe': Could not find 'bundler' (2.1.4) required by your /vagrant/mushroom-observer/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.1.4`
You must use Bundler 2 or greater with this lockfile.
You must use Bundler 2 or greater with this lockfile.
You must use Bundler 2 or greater with this lockfile.
RVM installed.  Run: source /home/vagrant/.rvm/scripts/rvm
```
If that's the expected output, consider adding a note telling users to ignore the error.

**Pull request merged**
