### PR TITLE
add virtual box bios gotcha

### PR DESCRIPTION
**Pull request by gete76**
Readme update for notes on enabling virtualization in the BIOS.

### CODE REVIEW

**Review by pellaea — APPROVED** [review]
Excellent!  Thanks, Greg.  Looks like PRs are working just fine for you.  If you like, we can give you permission to push to the main MushroomObserver repo (useful when collaborating with other developers on a PR, for example).  We prefer to add hooks in our local repos to prevent us from accidentally pushing to master, though.  I'll go ahead and merge this immediately.

**Comment by gete76** [comment]
Thanks @pellaea , Does that mean I should branch off of the MO org repo or my own?

**Comment by pellaea** [comment]
You can do either.  Even if you want to collaborate on a PR, you would just
have to make sure your collaborator had permission to push changes to your
PR wherever it is stored, right?  I'm just offering to give you permission
on the MO.org repo in case that is of interest to you.  Joe, Nimmo, Nathan
and I have been doing it that way for a while now, and with the hook in
place to prevent accidentally pushing to master, it has been working well.
I'll see if I can figure out how to give you permission to push to MO.org,
then it's entirely up to you.  We're open to your suggestions, of course,
too.

**Comment by gete76** [comment]
Oh cool, thanks! :)  I just wasn't sure if there was any hard fast rules to branching or branch naming, which I didn't see any.

**Comment by pellaea** [comment]
Done, I've invited you to be a "contributor" on MO.org github repo.  I
recommend adding this file to your local repo:

[mo]/.git/hooks/pre-commit:

#!/bin/sh
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "master" ]
then
  echo "Do not commit directly to the $branch branch"
  exit 1
fi

I wish we could figure out how to automatically add that.  I bet we could
get the mo-dev start-up script to do it.  Yeah, I might just give that a
shot later today.

Just saw your response -- I think there are as many PR naming conventions
as there are contributors... maybe more! :)  Joe likes to add the Pivotal
story ID.  Nimmo likes to prefix the PR with the username of the one who
started it.  I'm probably completely random.

**Comment by JoeCohen** [comment]
You're correct about branch names. No rules
My current practice: 
- I prefix my branch names with my initials (it makes it easier for me to find/switch to my branches, and might give helpful info to other developers)
- I postfix my branch names with the Pivotal story ID, if there is a story (integrates better with Pivotal).

**Comment by gete76** [comment]
Sounds good, I'll just do it the way I'm use to.

**Comment by JoeCohen** [comment]
Greg:
Once you get the git hook installed, it's easier to branch off the MO org
repo.
Joe

-----
My notes (quoting Nathan) on installing the git hook

> I just created a "git hook".  Git hooks are installed by users in some way
> typically in the directory ".git/hooks/".  The challenge with them is that
> they aren't actually versioned in the repository.  So they rely on users
> (or potentially scripts) doing the right thing.  The git hook I'm using is
> just:
> #!/bin/sh
> branch=$(git rev-parse --abbrev-ref HEAD)
> if [ "$branch" = "master" ]
> then
>     echo "Do not commit directly to the $branch branch"
>     exit 1
> fi
> That needs to be the file .git/hooks/pre-commit in your local repository
> and you need to make sure it's executable (chmod +x .git/hooks/pre-commit).
> Sharing git hooks is a bit challenging since ultimately all the mechanisms
> rely on users doing something directly (or potentially indirectly by
> running a script) to their local repos.  I think it makes sense for the
> project to have a set of git hooks and for mo-dev to try to get them placed
> correctly.  However, if/when they change we'll have to have people update
> their local repositories in some way.

**Pull request merged**
