### PR TITLE
Adds instructions for getting system working on windows

### PR DESCRIPTION
**Pull request by raysuelzer**
Adds instructions for getting system working on windows

### CODE REVIEW

**Comment by pellaea** [comment]
Hmmm, it's not merging automatically.  I'll have to look at this later.  I'm sure it'll be simple.  I'll cherry-pick it into ror4, too.

**Comment by raysuelzer** [comment]
You can always just copy paste the difs too. No need to get fancy :)

Ray Suelzer
Mobile: (312) 869-2665

**Comment by JoeCohen** [comment]
It's part of MushroomObserver/developer-startup, not
MushroomObserver/mushroom-observer.

*--Joe Cohen*

**Comment by pellaea** [comment]
Ah!  Thanks.  Then I can just cherry-pick Ray's commits into the correct
branch.  Will do later.

**Comment by raysuelzer** [comment]
Weird. Did it commit to the right place?

On Thursday, February 12, 2015, Jason Hollinger <notifications@github.com>
wrote:

> Ah! Thanks. Then I can just cherry-pick Ray's commits into the correct
> branch. Will do later.
>
> On Thu, Feb 12, 2015 at 4:09 PM, Joseph D. Cohen <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > It's part of MushroomObserver/developer-startup, not
> > MushroomObserver/mushroom-observer.
> >
> > *--Joe Cohen*
> >
> >
> > On Thu, Feb 12, 2015 at 3:50 PM, Raymond Suelzer <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > >
> > wrote:
> >
> > > You can always just copy paste the difs too. No need to get fancy :)
> > >
> > > Ray Suelzer
> > > Mobile: (312) 869-2665
> > >
> > > On Thu, Feb 12, 2015 at 3:35 PM, Jason Hollinger <
> > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > >
> > > wrote:
> > >
> > > > Hmmm, it's not merging automatically. I'll have to look at this
> later.
> > > I'm
> > > > sure it'll be simple. I'll cherry-pick it into ror4, too.
> > > >
> > > > --
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/MushroomObserver/developer-startup/pull/11#issuecomment-74176895
> > > >
> > >
> > > > .
> > > >
> > >
> > > --
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/MushroomObserver/developer-startup/pull/11#issuecomment-74178658
> > >
> >
> > > .
> > >
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/MushroomObserver/developer-startup/pull/11#issuecomment-74180841
> >
> > .
> >
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/MushroomObserver/developer-startup/pull/11#issuecomment-74182112>
> .
>


-- 
Ray Suelzer
Mobile: (312) 869-2665

**Comment by JoeCohen** [comment]
It should merge right into the developer-startup repo (and not into any
branch of the mushroom-observer repo).

*--Joe Cohen*

**Comment by pellaea** [comment]
Much confusion (mostly mine), but the fact remains it won't merge, and I'm looking into it now.

**Comment by pellaea** [comment]
Done.

**Pull request merged**
